### ISSUE TITLE
better permission denied error messages when not root/privileged

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#1325]
Sent to me by a coworker:

```$ /usr/share/bcc/tools/stackcount __alloc_fd
/virtual/main.c:8:1: error: could not open bpf map: Operation not permitted
is maps/hash map type enabled in your kernel?
BPF_HASH(counts, struct key_t);
^
/virtual/include/bcc/helpers.h:119:48: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                               ^
/virtual/main.c:9:1: error: could not open bpf map: Operation not permitted
is maps/stacktrace map type enabled in your kernel?
BPF_STACK_TRACE(stack_traces, 1024);
^
/virtual/include/bcc/helpers.h:154:3: note: expanded from macro 'BPF_STACK_TRACE'
  BPF_TABLE("stacktrace", int, struct bpf_stacktrace, _name, _max_entries);
  ^
/virtual/include/bcc/helpers.h:59:76: note: expanded from macro 'BPF_TABLE'
#define BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries) \
                                                                           ^
/virtual/include/bcc/helpers.h:55:4: note: expanded from macro '\
BPF_F_TABLE'
}; \
   ^
/virtual/main.c:16:19: error: bpf_table stack_traces failed to open
    key.stackid = stack_traces.get_stackid(ctx, BPF_F_REUSE_STACKID);
                  ^
3 errors generated.
Failed to compile BPF module
```

Is there a way we can improve this? Eg, if it said:

```
$ /usr/share/bcc/tools/stackcount __alloc_fd
Permission denied (not root or unprivileged). Use -v for verbose.
```

And the BPF() call could be passed a verbose flag (which would default to verbose, so tools that supported a "-v" could then overwrite it to be not verbose when -v was not used).

**Comment by palmtenor** [comment]
Maybe just proactively check for root privilege in say Python `BPF` class constructor? Most tools need root anyways, with very few exceptions like `tplist`

**Comment by aartiguptaa** [comment]
We use linux from scratch (4.4.69) and I was able to build bcc tools from source, (with clang, llvm, elfutils,....etc)
Now running a tool such as bitesize as root and see this error 

[root@optToolsBuild /common/bcc-build/share/bcc/tools]# ./bitesize
^C^C^C/virtual/main.c:14:1: error: could not open bpf map: Operation not permitted
is maps/histogram map type enabled in your kernel?
BPF_HISTOGRAM(dist, struct proc_key_t);
^
/virtual/include/bcc/helpers.h:164:37: note: expanded from macro 'BPF_HISTOGRAM'
  BPF_HISTX(__VA_ARGS__, BPF_HIST3, BPF_HIST2, BPF_HIST1)(__VA_ARGS__)
                                    ^
/virtual/main.c:15:1: error: could not open bpf map: Operation not permitted
is maps/hash map type enabled in your kernel?
BPF_HASH(commbyreq, struct request *, struct val_t);
^
/virtual/include/bcc/helpers.h:119:37: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                    ^
/virtual/main.c:22:9: error: bpf_table commbyreq failed to open
        commbyreq.update(&req, &val);
        ^
/virtual/main.c:31:12: error: bpf_table commbyreq failed to open
    valp = commbyreq.lookup(&req);
           ^
4 errors generated.
Traceback (most recent call last):
  File "./bitesize", line 63, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 289, in __init__
    self.debug, cflags_array, len(cflags_array))
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 1128, in cleanup
    if self.module:
AttributeError: 'BPF' object has no attribute 'module'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 1128, in cleanup
    if self.module:
AttributeError: 'BPF' object has no attribute 'module'

Any suggestions?

 uname -r
4.4.69

**Comment by yonghong-song** [comment]
Maybe you want to check your kernel has BPF enabled. See list of required
kernel configs in https://github.com/iovisor/bcc/blob/master/INSTALL.md.

**Comment by aartiguptaa** [comment]
I did, set all the kernel flags, recompiled the kernel and built packages such as clang, elfutils etc from scratch

 zgrep BPF  /proc/config.gz
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_BPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set
# CONFIG_GRKERNSEC_BPF_HARDEN is not set

Are all the tools available in linux 4.4 ?
@brendangregg 's  slide say bpf_perf_event_output was added in 4.4
If i have the latest version of bcc-tools from github, which tools are expected to work on 4.4?

P.s. also changed ulimit -l 
and executed the tools as root

any other suggestions? desperate to get this to work !

[root@optToolsBuild /common/bcc-build/share/bcc/tools]# uname -r
4.4.69

**Comment by aartiguptaa** [comment]
Once I disabled grsec the tools worked.  Does this mean the tools do not work with grsec enabled?

**Comment by yonghong-song** [comment]
If grsec has any similarity to selinux, yes, it is possible it is
configured to disable any syscall it does not explicitly configure/allow.
bpf syscalls could fall into this category. You can use strace to see
whether bpf syscall returns -EACCES.

**Comment by axot** [comment]
Hello, I got the same error with COS Linux. the strace shows

> bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_HASH, key_size=8, value_size=20, max_entries=10240}, 72) = -1 EPERM (Operation not permitted)

Any ideas?
