### ISSUE TITLE
xfsslower is broken in the newest bcc

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1766]
```
$ sudo /usr/share/bcc/tools/xfsslower 10
/virtual/main.c:136:37: error: cannot take the address of an rvalue of type 'typeof(struct dentry *)' (aka 'struct dentry *')
    bpf_probe_read(&de, sizeof(de), &({ typeof(struct dentry *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&valp->fp->f_path.dentry); _val; }));
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This seems related to #622, specifically https://github.com/iovisor/bcc/issues/622#issuecomment-386856427.

There may be more places where this doesn't work. Should we detect this and print a warning instead of breaking existing usage?

cc @pchaigno

**Comment by pchaigno** [comment]
Thanks for reporting this @bobrik!

I think this bug was introduced by #1737; it allows the bcc rewriter to track more external pointers (pointers to kernel addresses) through maps to replace them with calls to `bpf_probe_read`. Here, xfsslower was relying on the rewriter not being able to track some of those pointers (`bpf_probe_read(&de, sizeof(de), valp->fp->f_path.dentry)` syntax; the rewriter attempts to rewrite the dereference inside `bpf_probe_read`). #1767 should fix this.

I only ran the clang and smoke_tool tests which do not cover this particular tool. Hence I did not detect that it required a change. I'll do a second pass through all the tools that are not covered by the smoke_tool tests right now.

> There may be more places where this doesn't work. Should we detect this and print a warning instead of breaking existing usage?

The error is coming from Clang, but we may be able to provide a hint or detect it beforehand in the rewriter. I'm not sure that's the correct way to go though. 94d15bc889f1a5e50d030b606321a117536c20de changed the way deferences are rewritten and without it we would have any regressions in tools when the rewriter is improved (because without it, rewritten calls to `bpf_probe_read` wouldn't contain a dereference themselves). I'm not sure we can find another way to support anonymous struct/union though. @yonghong-song Any thoughts?

**Comment by yonghong-song** [comment]
I did not fully understand why rewriter tries to do bpf_probe_read for a `addr`, stores the result into a local, and took the address of the local and use it? I am referring to `&valp->fp->f_path.dentry`.
We should really rewrite `valp->fp`, right? Is this related to anonymous struct/union? If it is hard to track struct/union, the rewriter can always bail out. This is probably better than user compilation error.

**Comment by pchaigno** [comment]
> I did not fully understand why rewriter tries to do bpf_probe_read for a `addr`, stores the result into a local, and took the address of the local and use it? I am referring to `&valp->fp->f_path.dentry`.
We should really rewrite `valp->fp`, right?

@yonghong-song That's an old issue of the rewriter. For example, if you try the following program with an older version of bcc (e.g., 19e337295d2f587a03a1d6524a954252e90b1f42, before my series of PRs), it fails because it tries to rewrite `tp` instead of `tp->ptr`:
```python
from bcc import BPF

text = """
#include <linux/sched.h>
#include <uapi/linux/ptrace.h>

struct test_t {
	struct task_struct *ptr;
};

int count_sched(struct pt_regs *ctx, struct task_struct *prev) {
    struct test_t t = {};
    struct test_t *tp = &t;
    tp->ptr = prev;
    pid_t p = tp->ptr->pid;
    return (p != -1);
}
"""
b = BPF(text=text, debug=4)
fn = b.load_func("count_sched", BPF.KPROBE)
```
is rewritten to:
```
#include <linux/sched.h>
#include <uapi/linux/ptrace.h>

struct test_t {
	struct task_struct *ptr;
};

__attribute__((section(".bpf.fn.count_sched")))
int count_sched(struct pt_regs *ctx) { struct task_struct *prev = ctx->di;
    struct test_t t = {};
    struct test_t *tp = &t;
    ({ typeof(struct task_struct *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&tp->ptr); _val; }) = prev;
    pid_t p = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&({ typeof(struct task_struct *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&tp->ptr); _val; })->pid); _val; });
    return (p != -1);
}
```
and fails with the `expression is not assignable` error.

#1733 fixes this issue for most cases (including my above example). Unfortunately, we're still unable to track such external pointers as structure member through maps, which is what is happening in the OP here.

> Is this related to anonymous struct/union?

So, no. Not as far as I can see.

> If it is hard to track struct/union, the rewriter can always bail out. This is probably better than user compilation error.

I'm not sure how we could bail out without fully removing the rewriter for dereferences. I think it would be a shame; it works fine for most cases and it's getting better.

Overall, these issues (rewriter trying to rewrite too much) have always been there. Some of them may surface because of the recent pull requests, but it doesn't mean it was working as expected before. I'm convinced that if we carefully document/comment changes and increase our test coverage, we can handle most of the rewritter's issues *and* keep a maintainable piece of code. I'm not trying to handle corner cases; it's never going to be perfect at tracking external pointers anyway.

**Comment by yonghong-song** [comment]
I debugged a little bit about this `xfsslower.py` failure. In function `trace_fsync_entry`,
```
int trace_fsync_entry(struct pt_regs *ctx, struct file *file)
{
    ...
    val.fp = file;
    ...
}
```
`ProbeSetter` will insert the member declaration into `pt_regs_`.
```
  bool VisitMemberExpr(MemberExpr *M) {
    ptregs_->insert(M->getMemberDecl());
    return false;
  }
```

In function `trace_return`,
```
static int trace_return(struct pt_regs *ctx, int type)
{
   ...
    bpf_probe_read(&de, sizeof(de), &valp->fp->f_path.dentry);
   ...
}
```
valp->fp is hit and the following ProbeChecker function returns needs_probe true,
```
  bool VisitMemberExpr(MemberExpr *M) {
    if (ptregs_.find(M->getMemberDecl()) != ptregs_.end()) {
      needs_probe_ = true;
      return false;
    }
    return true;
  }
```

This seems not quite right. In ProberSetter, there is no AddrOf, and that is why it is added to pt_regs. But in later ProbeCheck, there is an AddrOf.

Maybe your previous checking levels of reference/dereference will help?
Maybe ptregs_ should not only Decl *, but also include Expr *?

**Comment by pchaigno** [comment]
> This seems not quite right. In ProberSetter, there is no AddrOf, and that is why it is added to pt_regs. But in later ProbeCheck, there is an AddrOf.

I'm not sure I follow you. What `AddrOf` are you referring to? Are you talking about #1752?

In #1752, there is indeed no check on `UO_AddrOf` in ProbeSetter because we only call it on the left hand side of assignments, so there shouldn't be any `UO_AddrOf` operations (lvalue required).

**Comment by yonghong-song** [comment]
I am referring to the AddrOf in `&valp->fp->f_path.dentry`.
