### ISSUE TITLE
cpudist - ImportError: cannot import name Tracepoint

### ISSUE THREAD

**Issue by jason-azze** [iovisor/bcc#924]
Using bcc-tools package version 0.2.0-280.git.b79b589 on Ubuntu 16.04.01

```
root@pioneer:~# cpudist
Traceback (most recent call last):
  File "/usr/share/bcc/tools/cpudist", line 15, in <module>
    from bcc import BPF, Tracepoint
ImportError: cannot import name Tracepoint
```

**Comment by brendangregg** [comment]
Tracepoints needs a newer kernel: http://www.slideshare.net/brendangregg/bpf-tracing-and-more/61 . Eg, should work on Ubuntu 16.10.

Sometimes bcc tools for older kernels will be under tools/old

I'm not sure why it failed in that matter though -- being unable to import Tracepoint.

**Comment by derek0883** [comment]
I Just checked out latest code from git.  got same error. 
```bash
$ uname -a
Linux ubuntu 4.9.0+ #44 SMP Fri Jan 27 11:52:01 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
$ sudo cp src/python/bcc/* /usr/lib/python2.7/dist-packages/
```
Code try to import Tracepoint
from bcc import BPF, Tracepoint

But Tracepoint is not in bcc modules, Did I missed something?

```python
import sys
before = [str(m) for m in sys.modules]
import bcc
after = [str(m) for m in sys.modules]
print [m for m in after if not m in before]
```

**Comment by goldshtn** [comment]
Yeah, it's a bug - the `Tracepoint` import should have been removed ages ago.
@brendangregg Yet again shows that we need automatic smoke tests to run the tools ...
