### ISSUE TITLE
in V0.10.0 error: ‘BPF_MAP_TYPE_CPUMAP’ was not declared in this scope

### ISSUE THREAD

**Issue by yinhongbo** [iovisor/bcc#2508]
In file included from /usr/lib/llvm-6.0/include/clang/Sema/CodeCompleteConsumer.h:21:0,
                 from /usr/lib/llvm-6.0/include/clang/Frontend/ASTUnit.h:26,
                 from /usr/lib/llvm-6.0/include/clang/Frontend/FrontendAction.h:24,
                 from /data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/b_frontend_action.h:24,
                 from /data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/b_frontend_action.cc:31:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h: In member function ‘clang::CXXScopeSpec& clang::DeclaratorChunk::MemberPointerTypeInfo::Scope()’:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h:1472:56: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       return *reinterpret_cast<CXXScopeSpec *>(ScopeMem);
                                                        ^
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h: In member function ‘const clang::CXXScopeSpec& clang::DeclaratorChunk::MemberPointerTypeInfo::Scope() const’:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h:1475:62: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       return *reinterpret_cast<const CXXScopeSpec *>(ScopeMem);
                                                              ^
In file included from /usr/lib/llvm-6.0/include/clang/Sema/CodeCompleteConsumer.h:21:0,
                 from /usr/lib/llvm-6.0/include/clang/Frontend/ASTUnit.h:26,
                 from /usr/lib/llvm-6.0/include/clang/Frontend/FrontendAction.h:24,
                 from /data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/tp_frontend_action.h:24,
                 from /data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/tp_frontend_action.cc:32:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h: In member function ‘clang::CXXScopeSpec& clang::DeclaratorChunk::MemberPointerTypeInfo::Scope()’:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h:1472:56: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       return *reinterpret_cast<CXXScopeSpec *>(ScopeMem);
                                                        ^
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h: In member function ‘const clang::CXXScopeSpec& clang::DeclaratorChunk::MemberPointerTypeInfo::Scope() const’:
/usr/lib/llvm-6.0/include/clang/Sema/DeclSpec.h:1475:62: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       return *reinterpret_cast<const CXXScopeSpec *>(ScopeMem);
                                                              ^
/data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/b_frontend_action.cc: In member function ‘bool ebpf::BTypeVisitor::VisitVarDecl(clang::VarDecl*)’:
/data00/src/code/cpath/tcc/bcc-0.10.0/src/cc/frontends/clang/b_frontend_action.cc:1209:18: error: ‘BPF_MAP_TYPE_CPUMAP’ was not declared in this scope

**Comment by palmtenor** [comment]
That is probably because the `bpf.h` in your `kernel-headers` do not have `BPF_MAP_TYPE_CPUMAP` defined.

**Comment by PaulFurtado** [comment]
@palmtenor so that symbol was introduced in linux 4.15. I'm hitting this issue on 4.14 right now as well.

bcc built great up through version v0.8.0. Are there any build flags to disable BPF_MAP_TYPE_CPUMAP in bcc at build time to get past this? The vast majority of bcc features likely continue working on 4.14 so it'd be a shame to require 4.15+ to continue using it. I'm guessing I can probably build bcc against the kernel 4.15+ headers and have it continue to work against 4.14, but it'd be great if there was a mechanism for dealing with this going forward

**Comment by yonghong-song** [comment]
@PaulFurtado the bcc build should not depend on system bpf.h header. It has its own in the repo (v0.8.0 and earlier) and in libbpf submodule (src/cc/libbpf/). Could you double check whether you have populated libbpf submodule properly for v0.9.0?

**Comment by PaulFurtado** [comment]
@yonghong-song got it, I'll give that a shot. We're building off of the github release archives right now, so I didn't even consider that there might be a submodule here.

**Comment by PaulFurtado** [comment]
@yonghong-song I built against the git tree and made sure the submodule was initialized and now it builds correctly. Thanks!

**Comment by yonghong-song** [comment]
Great!
