### ISSUE TITLE
fedora 25 install instructions currently lead to fail

### ISSUE THREAD

**Issue by ceeaspb** [iovisor/bcc#1430]
As far as I can tell, install instructions
https://github.com/iovisor/bcc/blob/master/INSTALL.md#fedora---binary
 for FC25 suggest running
``` sudo dnf update```

The problem is that this will currently update the kernel to 4.13 resulting in the same fail as in #1429.

```
$ sudo /usr/share/bcc/tools/offcputime
In file included from /virtual/main.c:3:
...
/lib/modules/4.13.8-100.fc25.x86_64/build/include/linux/string.h:21:27: error: arguments to BPF program definition must be named
extern char * strcpy(char *,const char *);
```

This probably didn't happen when the instructions were written but the update is open ended so it might fail in the future.

sadly downgrading doesn't work as we hit
```
    raise ValueError('NEVRA was already removed: %s' % old_nevra)
ValueError: NEVRA was already removed: lz4-0:r131-2.fc24.x86_64
```
https://bugzilla.redhat.com/show_bug.cgi?id=1478632
