### ISSUE TITLE
ubuntu 18.04 build failure

### ISSUE THREAD

**Issue by cleverchou** [iovisor/bcc#3039]
Hi

I am trying to do build on ubuntu 18.04, getting below error on running make command. 
PS: dependencies have installed

ccc@ebpf:~/bcc/bcc/build$ make
[  0%] Building C object src/cc/CMakeFiles/bpf-shared.dir/libbpf.c.o
In file included from /home/zhoucong/bcc/bcc/src/cc/libbpf.c:55:0:
/home/ccc/bcc/bcc/src/cc/bcc_libbpf_inc.h:8:11: fatal error: libbpf/src/bpf.h: "No such file or directory"
 # include "libbpf/src/bpf.h"
           ^~~~~~~~~~~~~~~~~~
compilation terminated.
src/cc/CMakeFiles/bpf-shared.dir/build.make:62: recipe for target 'src/cc/CMakeFiles/bpf-shared.dir/libbpf.c.o' failed
make[2]: *** [src/cc/CMakeFiles/bpf-shared.dir/libbpf.c.o] Error 1
CMakeFiles/Makefile2:157: recipe for target 'src/cc/CMakeFiles/bpf-shared.dir/all' failed
make[1]: *** [src/cc/CMakeFiles/bpf-shared.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
