### PR TITLE
examples: Use pid as filter instead of tid and make some improvements for stacksnoop.py

### PR DESCRIPTION
**Pull request by xingfeng2510**
For examples/stacksnoop.py:
- Use pid as filter instead of tid, keep consistent with -p option of other tools.
- Make some improvements (remove ctypes & 'b' prefixes).

### CODE REVIEW

**Comment by xingfeng2510** [comment]
ci failed due to following error (in mdflush.py, bio->bi_disk not found).
```
error: no member named 'bi_disk' in 'struct bio'
     struct gendisk *bi_disk = bio->bi_disk;
                              ~~~  ^
1 error generated.
Traceback (most recent call last):
   File "/bcc/tools/mdflush.py", line 54, in <module>
```

I guess CI runtime env (such as kernel version) had changed in recent days, and I will make another pull request to fix it.

**Comment by xingfeng2510** [comment]
CI build failure has been fixed in #3936.
