### PR TITLE
Fix 'tools/statsnoop' from failing to attach kprobes

### PR DESCRIPTION
**Pull request by sandip4n**
This fixes `tools/statsnoop` from failing to attach probes when the expected entry point for a system call cannot be found. This script uses the `stat`, `statfs` and `newstat` system calls, all of which must be implemented to be POSIX compliant. However, the names of the actual entry points for their respective implementations in the kernel might vary across architectures. For example, a `powerpc64` kernel does not define `sys_stat` but still provides the `stat` system call via `sys_newstat`. This causes the script to fail if it tries to attach a probe at `sys_stat`. We avoid this by performing some extra checks to see if these entry points exist.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by brendangregg** [comment]
thanks!

**Comment by nathanleclaire** [comment]
Hi @sandip4n, FYI, this causes an error on my machine (Linux 4.9.0 Debian) which does not happen without the change:

```
$ sudo ./tools/statsnoop.py                                              
Traceback (most recent call last):                                                     
  File "./tools/statsnoop.py", line 113, in <module>                        
    if BPF.ksymname("sys_stat") != -1:                                                 
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1035, in ksymname      
    return BPF._sym_cache(-1).resolve_name(None, name)                                 
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 74, in resolve_name 
    self.cache, module.encode("ascii"),                                              
AttributeError: 'NoneType' object has no attribute 'encode'    
```

I'm not sure if it's a bug or a problem on my end (e.g., needing to re-install BCC libraries), but I wanted to bring it to your awareness.

**Comment by pchaigno** [comment]
@nathanleclaire This bug was reported in #1054 and should be fixed with #1055 (which, according to your traceback, you don't have).

**Comment by sandip4n** [comment]
Hi @nathanleclaire,
If you look at the latest code for `src/python/bcc/__init__.py`, you will notice that there is already a check in line 85 to test if `module` is `None` introduced in #1055 as pointed out by @pchaigno.
```
if lib.bcc_symcache_resolve_name(
            self.cache, module.encode("ascii") if module else None,
            name.encode("ascii"), ct.pointer(addr)) < 0:
    return -1
```
According to the traceback you provided, this is exactly where the script crashes on your system even though the line numbers might not match because of later changes to this file. So, checking out the latest code and re-installing might fix your problem.

**Comment by nathanleclaire** [comment]
ok great, thanks y'all!
