### ISSUE TITLE
Build on Ubuntu 14.04 fails

### ISSUE THREAD

**Issue by stevenkaras** [iovisor/bcc#1410]
84757cec955d710d710c371a10cc689056a5ae81 introduced a bug when building from source on Ubuntu Trusty. This can be reproduced in a docker container using ubuntu:14.04.

```
In file included from /usr/include/c++/4.8/unordered_map:35:0,
                 from /root/bcc/src/cc/syms.h:22,
                 from /root/bcc/src/cc/bcc_syms.cc:34:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled wit$
 the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
[elided for brevity]
make[2]: *** [src/cc/CMakeFiles/bcc-loader-static.dir/bcc_syms.cc.o] Error 1
make[1]: *** [src/cc/CMakeFiles/bcc-loader-static.dir/all] Error 2
make: *** [all] Error 2
```

I am unsure if the bug arises from the CMake version packaged for Trusty, but I was able to build by reverting the commit.

**Comment by jonesmz** [comment]
You can set CXXFLAGS="${CXXFLAGS} -std=c++11" as an environment variable just before calling cmake.

I ran into the same bug when trying to build for centos7.

**Comment by hustcat** [comment]
Run  cmake3 before make:
```
cmake3 ..
```
