### PR TITLE
libbpf-tools: readahead: don't mark struct hist as static

### PR DESCRIPTION
**Pull request by jeromemarchand**
Libbpf readahead tool does not compile with bpftool v5.14. Since
commit 31332ccb756 ("bpftool: Stop emitting static variables in BPF
skeleton"), bpftool gen skeleton does not include static variables
into the skeleton file anymore.

Fixes the following compilation error:
readahead.c: In function 'main':
readahead.c:153:26: error: 'struct readahead_bpf__bss' has no member named 'hist'
  153 |         histp = &obj->bss->hist;
      |                          ^~

### CODE REVIEW

**Comment by davemarchevsky** [comment]
Thanks for fixing this! LGTM /cc @yonghong-song

File: libbpf-tools/readahead.bpf.c [hunk 1]
```diff
@@ -24,7 +24,7 @@ struct {
 	__uint(map_flags, BPF_F_NO_PREALLOC);
 } birth SEC(".maps");
 
-static struct hist hist;
+struct hist hist;
```
Comment (anakryiko) [inline libbpf-tools/readahead.bpf.c:27]: probably want to initialize explicitly to avoid problems with slightly older Clangs

Comment (jeromemarchand) [reply libbpf-tools/readahead.bpf.c:27]: Make sense. I'll update the MR.

**Review by anakryiko — APPROVED** [review]
LGTM, thanks!

**Comment by yonghong-song** [comment]
[buildbot, test this please]
