### ISSUE TITLE
ksymname doesn't work

### ISSUE THREAD

**Issue by tejom** [iovisor/bcc#1054]
I started trying out this library recently. I ran into a problem when trying to the python function `ksymname`. 

The error I get is:

        ("kernel address: %x" % b.ksymname("vfs_read"))
      File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1037, in ksymname
        return BPF._sym_cache(-1).resolve_name(None, name)
      File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 75, in resolve_name
        self.cache, module.encode("ascii"),
    AttributeError: 'NoneType' object has no attribute 'encode'

resolve_name function is called with the parameters None and name. resolve_name tries to use a function encode on module_name. I could create a pull request that checks the type before using encode on the parameters passed to resolve_name?

While I am making a post I might as well ask... What I was trying to do is call some kernel function that already exists. Including the header gave me an llvm error saying the function was external. I thought I might able to get the address of the function and use bpf_probe_read with a function pointer and the symbol address. That doesn't seem to work. Is what I am trying to do sound possible?

**Comment by goldshtn** [comment]
Yes, this is a bug -- I think it was introduced in 7b35436a when adding the `.encode`, but on my current Internet connection I can barely run `git pull` so I'll check later. 

Regarding your other question, you can't call arbitrary kernel functions from your BPF program. You can only use a closed set of kernel helpers like `bpf_ktime_get_ns`. Unless I'm misunderstanding something about your question?

**Comment by tejom** [comment]
Yeah that looks like it could be where it started.

And no I think you understood my question. I had a feeling that was true but thanks for confirming that.

**Comment by goldshtn** [comment]
OK, so this will be fixed in #1055. In the meantime, could you share a bit more detail on which function you're trying to trace and extract arguments from? Did you take a look at `fileslower`? It has some code for inspecting `file->f_path.dentry->d_name`.

**Comment by tejom** [comment]
Cool and sure I can.

I was trying something similar to that with ext4_file_open. Some of the variables I tried to print previously out gave me errors needing to use bpf_probe_read. I started using that to access any variable. When I used bpf_probe_read with f_path,dentry or d_name I got an error about lvalue(or rvalue? I don't have the original code I tried anymore) 

I took a look at the tools again and saw that one you mentioned and accessing file->f_path.dentry->d_name without using bpf_probe_read does work for me for getting the file name.

I was trying to use d_path, which is supposed to give you the full path, not just the file name. The error I get is an llvm error saying I'm using an external function that can't be resolved.

**Comment by goldshtn** [comment]
Maybe you could open a separate issue with the exact code and error that you're getting? It won't be the first time the rewrites does something quirky, and we might be able to find a workaround.

**Comment by tejom** [comment]
Sure I could do that. I think ill update my kernel,I was using an older rc kernel, and make sure it isn't something old. It sounds like it wasn't possible to begin with? I could post the code first anyway if your curious.

**Comment by goldshtn** [comment]
You can't call an arbitrary function, no. But I'm not sure why you couldn't extract the full path - does that require calling an external function?

**Comment by tejom** [comment]
Oh yeah d_path is a function that I was trying to use. http://lxr.free-electrons.com/source/fs/dcache.c#L3245 I should have clearer. Sorry about that.
