### ISSUE TITLE
Rewriter issue in 0.6.0: R1 invalid mem access 'inv'

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1858]
I have the following code:

```c
#include <linux/blkdev.h>
#include <linux/blk_types.h>

typedef struct disk_key {
		char disk[DISK_NAME_LEN];
		u8 op;
		u64 slot;
} disk_key_t;

// Histograms to record latencies
BPF_HISTOGRAM(io_latency, disk_key_t);

// Calculate request duration and store in appropriate histogram bucket
int trace_req_completion(struct pt_regs *ctx, struct request *req, unsigned int bytes) {
		u64 latency_slot = 12;

		disk_key_t latency_key = {};
		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), req->rq_disk->disk_name);

		io_latency.increment(latency_key);

		return 0;
}
```

In 0.5.0 in compiles down to this:

```c
#include <linux/blkdev.h>
#include <linux/blk_types.h>

typedef struct disk_key {
		char disk[DISK_NAME_LEN];
		u8 op;
		u64 slot;
} disk_key_t;

// Histograms to record latencies
BPF_HISTOGRAM(io_latency, disk_key_t);

// Calculate request duration and store in appropriate histogram bucket
__attribute__((section(".bpf.fn.trace_req_completion")))
int trace_req_completion(struct pt_regs *ctx) {
 struct request *req = ctx->di; unsigned int bytes = ctx->si;
		u64 latency_slot = 12;

		disk_key_t latency_key = {};
		latency_key.slot = latency_slot;
		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), ({ typeof(char [32]) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&({ typeof(struct gendisk *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&req->rq_disk); _val; })->disk_name); _val; }));

		({ typeof(io_latency.key) _key = latency_key; typeof(io_latency.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, 3), &_key); if (_leaf) (*_leaf)++; else { typeof(io_latency.leaf) _zleaf; __builtin_memset(&_zleaf, 0, sizeof(_zleaf)); _zleaf++; bpf_map_update_elem_(bpf_pseudo_fd(1, 3), &_key, &_zleaf, BPF_NOEXIST); } });

		return 0;
}
```

In 0.6.0 it compiles down to this:

```c
#include <linux/blkdev.h>
#include <linux/blk_types.h>

typedef struct disk_key {
		char disk[DISK_NAME_LEN];
		u8 op;
		u64 slot;
} disk_key_t;

// Histograms to record latencies
BPF_HISTOGRAM(io_latency, disk_key_t);

// Calculate request duration and store in appropriate histogram bucket
__attribute__((section(".bpf.fn.trace_req_completion")))
int trace_req_completion(struct pt_regs *ctx) {
 struct request *req = ctx->di; unsigned int bytes = ctx->si;
		u64 latency_slot = 12;

		disk_key_t latency_key = {};
		latency_key.slot = latency_slot;
		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), req->rq_disk->disk_name);

		({ typeof(io_latency.key) _key = latency_key; typeof(io_latency.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, 3), &_key); if (_leaf) (*_leaf)++; else { typeof(io_latency.leaf) _zleaf; __builtin_memset(&_zleaf, 0, sizeof(_zleaf)); _zleaf++; bpf_map_update_elem_(bpf_pseudo_fd(1, 3), &_key, &_zleaf, BPF_NOEXIST); } });

		return 0;
}
```

The difference is this:

```diff
- 		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), ({ typeof(char [32]) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&({ typeof(struct gendisk *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&req->rq_disk); _val; })->disk_name); _val; }));
+ 		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), req->rq_disk->disk_name);
```

While 0.5.0 works fine, on 0.6.0 I'm getting:

```
bpf: Failed to load program: Permission denied
0: (79) r1 = *(u64 *)(r1 +112)
1: (b7) r2 = 0
2: (7b) *(u64 *)(r10 -8) = r2
3: (7b) *(u64 *)(r10 -16) = r2
4: (7b) *(u64 *)(r10 -24) = r2
5: (7b) *(u64 *)(r10 -32) = r2
6: (7b) *(u64 *)(r10 -40) = r2
7: (7b) *(u64 *)(r10 -48) = r2
8: (79) r3 = *(u64 *)(r1 +192)
R1 invalid mem access 'inv'
```

Is that expected? Should I do my reads differently now?

cc @pchaigno, @yonghong-song

**Comment by yonghong-song** [comment]
@bobrik 0.6.0 has some issues if you use `bpf_probe_read` as it tries to rewrite the address_of operand of `bpf_probe_read`. This should be fixed with latest bcc trunk.

The workaround with 0.6.0 is to convert these `bpf_probe_read` to regular loads.
Could you try this?

**Comment by bobrik** [comment]
I'm using c2e2a26b8624492018a14d5eebd4a50b869c911f from today, so it doesn't look fixed.

Can you elaborate on converting to regular loads? I've tried:

```c
latency_key.disk = req->rq_disk->disk_name
```

But it fails:

```
/virtual/main.c:67:22: error: array type 'char [32]' is not assignable
    latency_key.disk = req->rq_disk->disk_name;
```

**Comment by pchaigno** [comment]
The following works with 0.6.0 and the latest trunk:
```python
from bcc import BPF

b = BPF(text="""
#include <linux/blkdev.h>
#include <linux/blk_types.h>

typedef struct disk_key {
		char disk[DISK_NAME_LEN];
		u8 op;
		u64 slot;
} disk_key_t;

// Histograms to record latencies
BPF_HISTOGRAM(io_latency, disk_key_t);

// Calculate request duration and store in appropriate histogram bucket
int trace_req_completion(struct pt_regs *ctx, struct request *req, unsigned int bytes) {
		u64 latency_slot = 12;

		disk_key_t latency_key = {};
		struct gendisk *disk = req->rq_disk;
		bpf_probe_read(&latency_key.disk, sizeof(latency_key.disk), &disk->disk_name);

		io_latency.increment(latency_key);

		return 0;
}
""")
b.load_func("trace_req_completion", BPF.KPROBE)
```
You can't do a `bpf_probe_read` on `req->rq_disk->disk_name` directly. You need to first retrieve the pointer to `req->rq_disk`.

It used to work because we used to rewrite dereferences even inside `bpf_probe_read` calls. We don't anymore and consider the user is responsible for rewriting everything inside `bpf_probe_read`. That makes it possible to handle complex case manually, without the rewriter intervening and breaking something.

**Comment by bobrik** [comment]
@pchaigno, thanks! This make sense and it worked.
